In [2]:
import numpy as np
import pandas as pd

In [4]:
dataset=pd.read_excel("C:\\Users\\USER\\Downloads\\data science practice\\
Lesson 5 - 2\\Olympic 2012 Medal Tally\\Olympic 2012 Medal Tally.xlsx")

In [6]:
dataset.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6'],
      dtype='object')

In [7]:
dataset

Unnamed: 0     Unnamed: 1    Unnamed: 2 Unnamed: 3   Unnamed: 4 Unnamed: 5  \
0         NaN        Country  Country Code       Year  Medal Tally        NaN   
1         NaN            NaN           NaN        NaN         Gold     Silver   
2         NaN  Great Britain           GBR       2012           29         17   
3         NaN         China            CHN       2012           38         28   
4         NaN         Russia           RUS       2012           24         25   
5         NaN  United States            US       2012           46         28   
6         NaN          Korea           KOR       2012           13          8   
7         NaN          Japan           JPN       2012            7         14   
8         NaN        Germany           GER       2012           11         11   

  Unnamed: 6  
0        NaN  
1     Bronze  
2         19  
3         22  
4         32  
5         29  
6          7  
7         17  
8         14

In [26]:
contry=np.array(['GBR' ,'CHN' ,'RUS' ,'US' ,'KOR' ,'JPN', 'GER'])
contry_Gold=np.array([29 ,38, 24, 46, 13, 7, 11])
contry_Silver=np.array([17, 28 ,25, 28 ,8 ,14 ,11])
contry_Bronze=np.array([19, 22, 32, 29, 7, 17, 14])

In [27]:
print(contry)
print(contry_Gold)
print(contry_Silver)
print(contry_Bronze)

['GBR' 'CHN' 'RUS' 'US' 'KOR' 'JPN' 'GER']
[29 38 24 46 13  7 11]
[17 28 25 28  8 14 11]
[19 22 32 29  7 17 14]


In [28]:
contry_with_max_gold=contry_Gold.argmax()

In [29]:
contry_with_max_gold

3

In [30]:
name_contry_with_max_gold=contry[contry_with_max_gold]

In [31]:
name_contry_with_max_gold

'US'

In [42]:
print(contry[contry_Gold>20])

['GBR' 'CHN' 'RUS' 'US']


In [47]:
for i in range(len(contry)):
    contri=contry[i]
    total=contry_Gold[i]+contry_Bronze[i]+contry_Silver[i]
    print("contt {} ,gm {} ,totla {}".format(contri,contry_Gold_all,total))

contt GBR ,gm 29 ,totla 65
contt CHN ,gm 38 ,totla 88
contt RUS ,gm 24 ,totla 81
contt US ,gm 46 ,totla 103
contt KOR ,gm 13 ,totla 28
contt JPN ,gm 7 ,totla 38
contt GER ,gm 11 ,totla 36


In [49]:
for i in range(len(contry)):
    cn=contry[i]
    ngm=contry_Gold[i]
    print("contry {} having {} np of gm".format(cn,ngm))

contry GBR having 29 np of gm
contry CHN having 38 np of gm
contry RUS having 24 np of gm
contry US having 46 np of gm
contry KOR having 13 np of gm
contry JPN having 7 np of gm
contry GER having 11 np of gm
